# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Phy 426 Fluid Mechanics
tagline:          'Fluid Mechanics'
description:      ''
url:              http://jklymak.github.io/Phy426/
baseurl:          '/Phy426'

author:
  name:           'Jody Klymak'
  url:            http://web.uvic.ca/~jklymak

paginate:         5
paginate_path: "blog/page:num"

github:
  repo:           https://github.com/jklymak/Phy426
